/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.15.v202410041637.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#include <v1/abdelfattah/examples/SomeIPBlSomeIPProxy.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace abdelfattah {
namespace examples {

std::shared_ptr<CommonAPI::SomeIP::Proxy> createSomeIPBlSomeIPProxy(
    const CommonAPI::SomeIP::Address &_address,
    const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection) {
    return std::make_shared< SomeIPBlSomeIPProxy>(_address, _connection);
}

void initializeSomeIPBlSomeIPProxy() {
    CommonAPI::SomeIP::AddressTranslator::get()->insert(
        "local:abdelfattah.examples.SomeIPBl:v1_0:abdelfattah.examples.SomeIPBl",
        0x1234, 0x1, 1, 0);
    CommonAPI::SomeIP::Factory::get()->registerProxyCreateMethod(
        "abdelfattah.examples.SomeIPBl:v1_0",
        &createSomeIPBlSomeIPProxy);
}

INITIALIZER(registerSomeIPBlSomeIPProxy) {
    CommonAPI::SomeIP::Factory::get()->registerInterface(initializeSomeIPBlSomeIPProxy);
}

SomeIPBlSomeIPProxy::SomeIPBlSomeIPProxy(
    const CommonAPI::SomeIP::Address &_address,
    const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection)
        : CommonAPI::SomeIP::Proxy(_address, _connection),
          firmwareAvailable_(*this, 0x1, CommonAPI::SomeIP::event_id_t(0x8001), CommonAPI::SomeIP::event_type_e::ET_EVENT , CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE, false, std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr), static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr)))
{
}

SomeIPBlSomeIPProxy::~SomeIPBlSomeIPProxy() {
}


SomeIPBlSomeIPProxy::FirmwareAvailableEvent& SomeIPBlSomeIPProxy::getFirmwareAvailableEvent() {
    return firmwareAvailable_;
}

void SomeIPBlSomeIPProxy::RequestDownload(CommonAPI::CallStatus &_internalCallStatus, bool &_result, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< bool, CommonAPI::EmptyDeployment> deploy_result(static_cast< CommonAPI::EmptyDeployment* >(nullptr));
    CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                bool,
                CommonAPI::EmptyDeployment
            >
        >
    >::callMethodWithReply(
        *this,
        CommonAPI::SomeIP::method_id_t(0x1),
        false,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        _internalCallStatus,
        deploy_result);
    _result = deploy_result.getValue();
}

std::future<CommonAPI::CallStatus> SomeIPBlSomeIPProxy::RequestDownloadAsync(RequestDownloadAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< bool, CommonAPI::EmptyDeployment> deploy_result(static_cast< CommonAPI::EmptyDeployment* >(nullptr));
    return CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                bool,
                CommonAPI::EmptyDeployment
            >
        >
    >::callMethodAsync(
        *this,
        CommonAPI::SomeIP::method_id_t(0x1),
        false,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        [_callback] (CommonAPI::CallStatus _internalCallStatus, CommonAPI::Deployable< bool, CommonAPI::EmptyDeployment > _result) {
            if (_callback)
                _callback(_internalCallStatus, _result.getValue());
        },
        std::make_tuple(deploy_result));
}

void SomeIPBlSomeIPProxy::RequestData(uint32_t _NoOfBytes, CommonAPI::CallStatus &_internalCallStatus, SomeIPBl::ByteArray &_message, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< uint32_t, CommonAPI::SomeIP::IntegerDeployment<uint32_t>> deploy_NoOfBytes(_NoOfBytes, static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr));
    CommonAPI::Deployable< SomeIPBl::ByteArray, ::v1::abdelfattah::examples::SomeIPBl_::ByteArrayDeployment_t> deploy_message(static_cast< ::v1::abdelfattah::examples::SomeIPBl_::ByteArrayDeployment_t* >(nullptr));
    CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                uint32_t,
                CommonAPI::SomeIP::IntegerDeployment<uint32_t>
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                SomeIPBl::ByteArray,
                ::v1::abdelfattah::examples::SomeIPBl_::ByteArrayDeployment_t
            >
        >
    >::callMethodWithReply(
        *this,
        CommonAPI::SomeIP::method_id_t(0x2),
        false,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_NoOfBytes,
        _internalCallStatus,
        deploy_message);
    _message = deploy_message.getValue();
}

std::future<CommonAPI::CallStatus> SomeIPBlSomeIPProxy::RequestDataAsync(const uint32_t &_NoOfBytes, RequestDataAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< uint32_t, CommonAPI::SomeIP::IntegerDeployment<uint32_t>> deploy_NoOfBytes(_NoOfBytes, static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr));
    CommonAPI::Deployable< SomeIPBl::ByteArray, ::v1::abdelfattah::examples::SomeIPBl_::ByteArrayDeployment_t> deploy_message(static_cast< ::v1::abdelfattah::examples::SomeIPBl_::ByteArrayDeployment_t* >(nullptr));
    return CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                uint32_t,
                CommonAPI::SomeIP::IntegerDeployment<uint32_t>
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                SomeIPBl::ByteArray,
                ::v1::abdelfattah::examples::SomeIPBl_::ByteArrayDeployment_t
            >
        >
    >::callMethodAsync(
        *this,
        CommonAPI::SomeIP::method_id_t(0x2),
        false,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_NoOfBytes,
        [_callback] (CommonAPI::CallStatus _internalCallStatus, CommonAPI::Deployable< SomeIPBl::ByteArray, ::v1::abdelfattah::examples::SomeIPBl_::ByteArrayDeployment_t > _message) {
            if (_callback)
                _callback(_internalCallStatus, _message.getValue());
        },
        std::make_tuple(deploy_message));
}

void SomeIPBlSomeIPProxy::getOwnVersion(uint16_t& ownVersionMajor, uint16_t& ownVersionMinor) const {
    ownVersionMajor = 1;
    ownVersionMinor = 0;
}

std::future<void> SomeIPBlSomeIPProxy::getCompletionFuture() {
    return CommonAPI::SomeIP::Proxy::getCompletionFuture();
}

} // namespace examples
} // namespace abdelfattah
} // namespace v1
