/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.15.v202410041637.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#include <v1/abdelfattah/examples/SomeIPBlSomeIPStubAdapter.hpp>
#include <v1/abdelfattah/examples/SomeIPBl.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace abdelfattah {
namespace examples {

std::shared_ptr<CommonAPI::SomeIP::StubAdapter> createSomeIPBlSomeIPStubAdapter(
                   const CommonAPI::SomeIP::Address &_address,
                   const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
                   const std::shared_ptr<CommonAPI::StubBase> &_stub) {
    return std::make_shared< SomeIPBlSomeIPStubAdapter<::v1::abdelfattah::examples::SomeIPBlStub>>(_address, _connection, _stub);
}

void initializeSomeIPBlSomeIPStubAdapter() {
    CommonAPI::SomeIP::AddressTranslator::get()->insert(
        "local:abdelfattah.examples.SomeIPBl:v1_0:abdelfattah.examples.SomeIPBl",
         0x1234, 0x1, 1, 0);
    CommonAPI::SomeIP::Factory::get()->registerStubAdapterCreateMethod(
        "abdelfattah.examples.SomeIPBl:v1_0",
        &createSomeIPBlSomeIPStubAdapter);
}

INITIALIZER(registerSomeIPBlSomeIPStubAdapter) {
    CommonAPI::SomeIP::Factory::get()->registerInterface(initializeSomeIPBlSomeIPStubAdapter);
}

} // namespace examples
} // namespace abdelfattah
} // namespace v1
