/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.15.v202410041619.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_ABDELFATTAH_EXAMPLES_Some_IP_Bl_PROXY_BASE_HPP_
#define V1_ABDELFATTAH_EXAMPLES_Some_IP_Bl_PROXY_BASE_HPP_

#include <v1/abdelfattah/examples/SomeIPBl.hpp>



#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <cstdint>
#include <vector>

#include <CommonAPI/Event.hpp>
#include <CommonAPI/Proxy.hpp>
#include <functional>
#include <future>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace abdelfattah {
namespace examples {

class SomeIPBlProxyBase
    : virtual public CommonAPI::Proxy {
public:
    typedef CommonAPI::Event<
        uint32_t, uint32_t
    > FirmwareAvailableEvent;

    typedef std::function<void(const CommonAPI::CallStatus&, const bool&)> RequestDownloadAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&, const SomeIPBl::ByteArray&)> RequestDataAsyncCallback;

    virtual FirmwareAvailableEvent& getFirmwareAvailableEvent() = 0;
    virtual void RequestDownload(CommonAPI::CallStatus &_internalCallStatus, bool &_result, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> RequestDownloadAsync(RequestDownloadAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual void RequestData(uint32_t _NoOfBytes, CommonAPI::CallStatus &_internalCallStatus, SomeIPBl::ByteArray &_message, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> RequestDataAsync(const uint32_t &_NoOfBytes, RequestDataAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;

    virtual std::future<void> getCompletionFuture() = 0;
};

} // namespace examples
} // namespace abdelfattah
} // namespace v1


// Compatibility
namespace v1_0 = v1;

#endif // V1_ABDELFATTAH_EXAMPLES_Some_IP_Bl_PROXY_BASE_HPP_
