/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.15.v202410041619.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_ABDELFATTAH_EXAMPLES_SOME_IP_BL_HPP_
#define V1_ABDELFATTAH_EXAMPLES_SOME_IP_BL_HPP_




#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/Types.hpp>
#include <cstdint>
#include <vector>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace abdelfattah {
namespace examples {

class SomeIPBl {
public:
    virtual ~SomeIPBl() { }

    static inline const char* getInterface();
    static inline CommonAPI::Version getInterfaceVersion();
    typedef std::vector< uint8_t> ByteArray;
};

const char* SomeIPBl::getInterface() {
    return ("abdelfattah.examples.SomeIPBl:v1_0");
}

CommonAPI::Version SomeIPBl::getInterfaceVersion() {
    return CommonAPI::Version(1, 0);
}


} // namespace examples
} // namespace abdelfattah
} // namespace v1

namespace CommonAPI {
}


// Compatibility
namespace v1_0 = v1;

#endif // V1_ABDELFATTAH_EXAMPLES_SOME_IP_BL_HPP_
