/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.15.v202410041637.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#ifndef V1_ABDELFATTAH_EXAMPLES_SOME_IP_BL_SOMEIP_STUB_ADAPTER_HPP_
#define V1_ABDELFATTAH_EXAMPLES_SOME_IP_BL_SOMEIP_STUB_ADAPTER_HPP_

#include <v1/abdelfattah/examples/SomeIPBlStub.hpp>
#include <v1/abdelfattah/examples/SomeIPBlSomeIPDeployment.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>
#include <CommonAPI/SomeIP/StubAdapterHelper.hpp>
#include <CommonAPI/SomeIP/StubAdapter.hpp>
#include <CommonAPI/SomeIP/Factory.hpp>
#include <CommonAPI/SomeIP/Types.hpp>
#include <CommonAPI/SomeIP/Constants.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace abdelfattah {
namespace examples {

template <typename _Stub = ::v1::abdelfattah::examples::SomeIPBlStub, typename... _Stubs>
class SomeIPBlSomeIPStubAdapterInternal
    : public virtual SomeIPBlStubAdapter,
      public CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...>,
      public std::enable_shared_from_this< SomeIPBlSomeIPStubAdapterInternal<_Stub, _Stubs...>>
{
public:
    typedef CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...> SomeIPBlSomeIPStubAdapterHelper;

    ~SomeIPBlSomeIPStubAdapterInternal() {
        deactivateManagedInstances();
        SomeIPBlSomeIPStubAdapterHelper::deinit();
    }

    void fireFirmwareAvailableEvent(const uint32_t &_fileSize, const uint32_t &_checksum);

    void deactivateManagedInstances() {}
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v1::abdelfattah::examples::SomeIPBlStub,
        CommonAPI::Version
    > getSomeIPBlInterfaceVersionStubDispatcher;

    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::abdelfattah::examples::SomeIPBlStub,
        std::tuple< >,
        std::tuple< bool>,
        std::tuple< >,
        std::tuple< CommonAPI::EmptyDeployment>
    > requestDownloadStubDispatcher;
    
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::abdelfattah::examples::SomeIPBlStub,
        std::tuple< uint32_t>,
        std::tuple< SomeIPBl::ByteArray>,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint32_t>>,
        std::tuple< ::v1::abdelfattah::examples::SomeIPBl_::ByteArrayDeployment_t>
    > requestDataStubDispatcher;
    
    SomeIPBlSomeIPStubAdapterInternal(
        const CommonAPI::SomeIP::Address &_address,
        const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
        const std::shared_ptr<CommonAPI::StubBase> &_stub):
        CommonAPI::SomeIP::StubAdapter(_address, _connection),
        SomeIPBlSomeIPStubAdapterHelper(
            _address,
            _connection,
            std::dynamic_pointer_cast< SomeIPBlStub>(_stub)),
        getSomeIPBlInterfaceVersionStubDispatcher(&SomeIPBlStub::lockInterfaceVersionAttribute, &SomeIPBlStub::getInterfaceVersion, false, true),
        requestDownloadStubDispatcher(
            &SomeIPBlStub::RequestDownload,
            false,
            _stub->hasElement(1),
            std::make_tuple(),
            std::make_tuple(static_cast< CommonAPI::EmptyDeployment* >(nullptr)))
        
        ,
        requestDataStubDispatcher(
            &SomeIPBlStub::RequestData,
            false,
            _stub->hasElement(2),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr)),
            std::make_tuple(static_cast< ::v1::abdelfattah::examples::SomeIPBl_::ByteArrayDeployment_t* >(nullptr)))
        
    {
        SomeIPBlSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x1) }, &requestDownloadStubDispatcher );
        SomeIPBlSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x2) }, &requestDataStubDispatcher );
        // Provided events/fields
        {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(0x1));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0x8001), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_EVENT, CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE);
        }
    }

    // Register/Unregister event handlers for selective broadcasts
    void registerSelectiveEventHandlers();
    void unregisterSelectiveEventHandlers();

};

template <typename _Stub, typename... _Stubs>
void SomeIPBlSomeIPStubAdapterInternal<_Stub, _Stubs...>::fireFirmwareAvailableEvent(const uint32_t &_fileSize, const uint32_t &_checksum) {
    CommonAPI::Deployable< uint32_t, CommonAPI::SomeIP::IntegerDeployment<uint32_t>> deployed_fileSize(_fileSize, static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr));
    CommonAPI::Deployable< uint32_t, CommonAPI::SomeIP::IntegerDeployment<uint32_t>> deployed_checksum(_checksum, static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<CommonAPI::SomeIP::SerializableArguments<  CommonAPI::Deployable< uint32_t, CommonAPI::SomeIP::IntegerDeployment<uint32_t> > 
    ,  CommonAPI::Deployable< uint32_t, CommonAPI::SomeIP::IntegerDeployment<uint32_t> > 
    >>
        ::sendEvent(
            *this,
            CommonAPI::SomeIP::event_id_t(0x8001),
            false,
             deployed_fileSize 
            ,  deployed_checksum 
    );
}


template <typename _Stub, typename... _Stubs>
void SomeIPBlSomeIPStubAdapterInternal<_Stub, _Stubs...>::registerSelectiveEventHandlers() {

}

template <typename _Stub, typename... _Stubs>
void SomeIPBlSomeIPStubAdapterInternal<_Stub, _Stubs...>::unregisterSelectiveEventHandlers() {

}

template <typename _Stub = ::v1::abdelfattah::examples::SomeIPBlStub, typename... _Stubs>
class SomeIPBlSomeIPStubAdapter
    : public SomeIPBlSomeIPStubAdapterInternal<_Stub, _Stubs...> {
public:
    SomeIPBlSomeIPStubAdapter(const CommonAPI::SomeIP::Address &_address,
                                            const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
                                            const std::shared_ptr<CommonAPI::StubBase> &_stub)
        : CommonAPI::SomeIP::StubAdapter(_address, _connection),
          SomeIPBlSomeIPStubAdapterInternal<_Stub, _Stubs...>(_address, _connection, _stub) {
    }
};

} // namespace examples
} // namespace abdelfattah
} // namespace v1

#endif // V1_ABDELFATTAH_EXAMPLES_Some_IP_Bl_SOMEIP_STUB_ADAPTER_HPP_
