/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.15.v202410041619.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_ABDELFATTAH_EXAMPLES_Some_IP_Bl_STUB_HPP_
#define V1_ABDELFATTAH_EXAMPLES_Some_IP_Bl_STUB_HPP_

#include <functional>
#include <sstream>




#include <v1/abdelfattah/examples/SomeIPBl.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <cstdint>
#include <unordered_set>
#include <vector>


#include <CommonAPI/Stub.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace abdelfattah {
namespace examples {

/**
 * Receives messages from remote and handles all dispatching of deserialized calls
 * to a stub for the service SomeIPBl. Also provides means to send broadcasts
 * and attribute-changed-notifications of observable attributes as defined by this service.
 * An application developer should not need to bother with this class.
 */
class SomeIPBlStubAdapter
    : public virtual CommonAPI::StubAdapter,
      public virtual SomeIPBl {
 public:
    /**
    * Sends a broadcast event for FirmwareAvailable. Should not be called directly.
    * Instead, the "fire<broadcastName>Event" methods of the stub should be used.
    */
    virtual void fireFirmwareAvailableEvent(const uint32_t &_fileSize, const uint32_t &_checksum) = 0;


    virtual void deactivateManagedInstances() = 0;


protected:
    /**
     * Defines properties for storing the ClientIds of clients / proxies that have
     * subscribed to the selective broadcasts
     */

};

/**
 * Defines the necessary callbacks to handle remote set events related to the attributes
 * defined in the IDL description for SomeIPBl.
 * For each attribute two callbacks are defined:
 * - a verification callback that allows to verify the requested value and to prevent setting
 *   e.g. an invalid value ("onRemoteSet<AttributeName>").
 * - an action callback to do local work after the attribute value has been changed
 *   ("onRemote<AttributeName>Changed").
 *
 * This class and the one below are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class SomeIPBlStubRemoteEvent
{
public:
    virtual ~SomeIPBlStubRemoteEvent() { }

};

/**
 * Defines the interface that must be implemented by any class that should provide
 * the service SomeIPBl to remote clients.
 * This class and the one above are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class SomeIPBlStub
    : public virtual CommonAPI::Stub<SomeIPBlStubAdapter, SomeIPBlStubRemoteEvent>
{
public:
    typedef std::function<void (bool _result)> RequestDownloadReply_t;
    typedef std::function<void (SomeIPBl::ByteArray _message)> RequestDataReply_t;

    virtual ~SomeIPBlStub() {}
    void lockInterfaceVersionAttribute(bool _lockAccess) { static_cast<void>(_lockAccess); }
    bool hasElement(const uint32_t _id) const {
        return (_id < 3);
    }
    virtual const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) = 0;

    /// Sends a broadcast event for FirmwareAvailable.
    virtual void fireFirmwareAvailableEvent(const uint32_t &_fileSize, const uint32_t &_checksum) {
        auto stubAdapter = CommonAPI::Stub<SomeIPBlStubAdapter, SomeIPBlStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->fireFirmwareAvailableEvent(_fileSize, _checksum);
    }
    /// This is the method that will be called on remote calls on the method RequestDownload.
    virtual void RequestDownload(const std::shared_ptr<CommonAPI::ClientId> _client, RequestDownloadReply_t _reply) = 0;
    /// This is the method that will be called on remote calls on the method RequestData.
    virtual void RequestData(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _NoOfBytes, RequestDataReply_t _reply) = 0;


    using CommonAPI::Stub<SomeIPBlStubAdapter, SomeIPBlStubRemoteEvent>::initStubAdapter;
    typedef CommonAPI::Stub<SomeIPBlStubAdapter, SomeIPBlStubRemoteEvent>::StubAdapterType StubAdapterType;
    typedef CommonAPI::Stub<SomeIPBlStubAdapter, SomeIPBlStubRemoteEvent>::RemoteEventHandlerType RemoteEventHandlerType;
    typedef SomeIPBlStubRemoteEvent RemoteEventType;
    typedef ::v1::abdelfattah::examples::SomeIPBl StubInterface;
};

} // namespace examples
} // namespace abdelfattah
} // namespace v1


// Compatibility
namespace v1_0 = v1;

#endif // V1_ABDELFATTAH_EXAMPLES_Some_IP_Bl_STUB_HPP_
